### ISSUE TITLE
Profile the clinical data binning aggregation step

### ISSUE THREAD

**Issue by alisman** [cBioPortal/rfc80-team#4]

**Comment by onursumer** [comment]
Profiled `api/column-store/clinical-data-bin-counts/fetch` endpoint by using the [columnar-clinical-data-binner](https://github.com/onursumer/cbioportal/tree/columnar-clinical-data-binner) branch and a cloud [clickhouse instance](https://console.clickhouse.cloud/services/ed99869f-2c73-4b9e-a6a3-e04aeb542e20/console/database/sling_db_2024_04_16_original/) which utilizes regular views only. 

Fetch method being invoked

```JavaScript
fetch("http://localhost:8080/api/column-store/clinical-data-bin-counts/fetch?dataBinMethod=STATIC", {
  "headers": {
    "accept": "application/json",
    "accept-language": "en-US,en;q=0.9,tr;q=0.8,fi;q=0.7",
    "content-type": "application/json",
    "sec-ch-ua": "\"Chromium\";v=\"124\", \"Google Chrome\";v=\"124\", \"Not-A.Brand\";v=\"99\"",
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": "\"macOS\"",
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "same-origin"
  },
  "referrer": "http://localhost:8080/study/summary?id=genie_public",
  "referrerPolicy": "strict-origin-when-cross-origin",
  "body": "{\"attributes\":[{\"attributeId\":\"MUTATION_COUNT\",\"disableLogScale\":false,\"showNA\":true},{\"attributeId\":\"FRACTION_GENOME_ALTERED\",\"disableLogScale\":false,\"showNA\":true},{\"attributeId\":\"AGE_AT_SEQ_REPORT\",\"disableLogScale\":false,\"showNA\":true},{\"attributeId\":\"INT_CONTACT\",\"disableLogScale\":false,\"showNA\":true},{\"attributeId\":\"INT_DOD\",\"disableLogScale\":false,\"showNA\":true},{\"attributeId\":\"YEAR_DEATH\",\"disableLogScale\":false,\"showNA\":true},{\"attributeId\":\"YEAR_CONTACT\",\"disableLogScale\":false,\"showNA\":true}],\"studyViewFilter\":{\"studyIds\":[\"genie_public\"],\"alterationFilter\":{\"copyNumberAlterationEventTypes\":{\"AMP\":true,\"HOMDEL\":true},\"mutationEventTypes\":{\"any\":true},\"structuralVariants\":null,\"includeDriver\":true,\"includeVUS\":true,\"includeUnknownOncogenicity\":true,\"includeUnknownTier\":true,\"includeGermline\":true,\"includeSomatic\":true,\"includeUnknownStatus\":true,\"tiersBooleanMap\":{}}}}",
  "method": "POST",
  "mode": "cors",
  "credentials": "include"
});
```

Overview

![clinical-data-bin-counts_2024-05-16](https://github.com/cBioPortal/rfc80-team/assets/3604198/6ebd2bc2-7c5c-4668-be14-b62f055abf7f)

`getFilteredSamples` CPU time is about 31%

<img width="494" alt="getFilteredSamples" src="https://github.com/cBioPortal/rfc80-team/assets/3604198/c2914c8b-66c3-4b45-9037-685355fd3a27">

`calcuNaDataBin` CPU time is about 5%

<img width="374" alt="calcNaData" src="https://github.com/cBioPortal/rfc80-team/assets/3604198/b38e306e-60b9-4fac-9706-8eb6107677b9">

`countNAs` CPU time is about 5% as well

<img width="346" alt="countNAs" src="https://github.com/cBioPortal/rfc80-team/assets/3604198/52572543-b41c-4cf9-9be9-ca7623b44957">

It should be relatively easier to calculate/count NAs with some SQL queries instead of fetching the filtered sample data and processing it in Java. That way we may be able to improve the performance of this endpoint by 30 to 40 percent.

**Comment by inodb** [comment]
Doing https://github.com/cBioPortal/rfc80-team/issues/16 now before doing more profiling
