### ISSUE TITLE
Normalization issue on clinical-data-counts service

### ISSUE THREAD

**Issue by alisman** [cBioPortal/rfc80-team#40]
The legacy code normalizes TRUE->True and FALSE-False.  We should find this in old codebase and make sure we handle it.  

<img width="1865" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXRiQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c2cc16c8ff77f2edc40e4711140d8e2554c68614/image.png" alt="image.png" />

```
fetch("https://genie-public-beta1.cbioportal.org/api/column-store/clinical-data-bin-counts/fetch?dataBinMethod=STATIC", {
  "headers": {
    "accept": "application/json",
    "accept-language": "en-US,en;q=0.9",
    "cache-control": "no-cache",
    "content-type": "application/json",
    "pragma": "no-cache",
    "priority": "u=1, i",
    "sec-ch-ua": "\"Not)A;Brand\";v=\"99\", \"Google Chrome\";v=\"127\", \"Chromium\";v=\"127\"",
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": "\"macOS\"",
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "same-site"
  },
  "referrer": "https://genie-public-beta.cbioportal.org/",
  "referrerPolicy": "strict-origin-when-cross-origin",
  "body": "{\"attributes\":[{\"attributeId\":\"MUTATION_COUNT\",\"disableLogScale\":false,\"showNA\":false},{\"attributeId\":\"FRACTION_GENOME_ALTERED\",\"disableLogScale\":false,\"showNA\":false},{\"attributeId\":\"AGE_AT_SEQ_REPORT\",\"disableLogScale\":false,\"showNA\":false},{\"attributeId\":\"INT_CONTACT\",\"disableLogScale\":false,\"showNA\":false},{\"attributeId\":\"INT_DOD\",\"disableLogScale\":false,\"showNA\":false},{\"attributeId\":\"YEAR_DEATH\",\"disableLogScale\":false,\"showNA\":false},{\"attributeId\":\"YEAR_CONTACT\",\"disableLogScale\":false,\"showNA\":false}],\"studyViewFilter\":{\"studyIds\":[\"genie_public\"],\"alterationFilter\":{\"copyNumberAlterationEventTypes\":{\"AMP\":true,\"HOMDEL\":true},\"mutationEventTypes\":{\"any\":true},\"structuralVariants\":null,\"includeDriver\":true,\"includeVUS\":true,\"includeUnknownOncogenicity\":true,\"includeUnknownTier\":true,\"includeGermline\":true,\"includeSomatic\":true,\"includeUnknownStatus\":true,\"tiersBooleanMap\":{}}}}",
  "method": "POST",
  "mode": "cors",
  "credentials": "omit"
});
```

**Comment by onursumer** [comment]
Looks like this was handled by mysql automatically because the queries are case insensitive.

For example `select count(*) from clinical_patient where ATTR_VALUE='False'` and `select count(*) from clinical_patient where ATTR_VALUE='FALSE'` returns the same number in mysql. However `select count(*) from clinical_data_derived where attribute_value='FALSE'` and `select count(*) from clinical_data_derived where attribute_value='False'` return two different numbers in clickhouse.

We can probably generalize the sql below and normalize boolean values in addition to NA values.

https://github.com/cBioPortal/cbioportal/blob/956fb3379fb4d03559da1ecb355b0ee711fc0693/src/main/resources/org/cbioportal/persistence/mybatisclickhouse/StudyViewMapper.xml#L631-L640

```XML
<sql id="normalizeAttributeValueNA">
    if(
      <include refid="isAttributeValueNA">
          <property name="attribute_value" value="${attribute_value}"/>
      </include>,
      'NA',
      ${attribute_value}
    )
    AS ${as_value}
</sql>
```

**Comment by onursumer** [comment]
A better solution would be to normalize boolean values when importing into the database to make sure that boolean values are always in the form of `True` or `False`.
